# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'makine.ui'
#
# Created: Tue Jan 16 05:26:40 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1167, 903)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1161, 901))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 361, 281))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 50, 101, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.leRusRosVeriMiktari1 = QtGui.QLineEdit(self.groupBox)
        self.leRusRosVeriMiktari1.setGeometry(QtCore.QRect(110, 50, 231, 29))
        self.leRusRosVeriMiktari1.setObjectName(_fromUtf8("leRusRosVeriMiktari1"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 101, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.leRusRosVeriAralk1 = QtGui.QLineEdit(self.groupBox)
        self.leRusRosVeriAralk1.setGeometry(QtCore.QRect(110, 100, 231, 29))
        self.leRusRosVeriAralk1.setObjectName(_fromUtf8("leRusRosVeriAralk1"))
        self.leRusRosVeriAralk11 = QtGui.QLineEdit(self.groupBox)
        self.leRusRosVeriAralk11.setGeometry(QtCore.QRect(110, 150, 231, 29))
        self.leRusRosVeriAralk11.setObjectName(_fromUtf8("leRusRosVeriAralk11"))
        self.btnRusRosRandomVeri1 = QtGui.QPushButton(self.groupBox)
        self.btnRusRosRandomVeri1.setGeometry(QtCore.QRect(10, 220, 341, 41))
        self.btnRusRosRandomVeri1.setObjectName(_fromUtf8("btnRusRosRandomVeri1"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 91, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 20, 121, 281))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.btnRusRosVeriYukle1 = QtGui.QPushButton(self.groupBox_2)
        self.btnRusRosVeriYukle1.setGeometry(QtCore.QRect(20, 20, 81, 251))
        self.btnRusRosVeriYukle1.setObjectName(_fromUtf8("btnRusRosVeriYukle1"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(530, 20, 601, 281))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.twRusRosVeri1 = QtGui.QTableWidget(self.groupBox_3)
        self.twRusRosVeri1.setGeometry(QtCore.QRect(10, 20, 581, 251))
        self.twRusRosVeri1.setObjectName(_fromUtf8("twRusRosVeri1"))
        self.twRusRosVeri1.setColumnCount(0)
        self.twRusRosVeri1.setRowCount(0)
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 310, 361, 271))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 91, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.leRusRosVeriMiktari2 = QtGui.QLineEdit(self.groupBox_4)
        self.leRusRosVeriMiktari2.setGeometry(QtCore.QRect(100, 50, 241, 29))
        self.leRusRosVeriMiktari2.setObjectName(_fromUtf8("leRusRosVeriMiktari2"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 91, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.leRusRosVeriAralk2 = QtGui.QLineEdit(self.groupBox_4)
        self.leRusRosVeriAralk2.setGeometry(QtCore.QRect(100, 100, 241, 29))
        self.leRusRosVeriAralk2.setObjectName(_fromUtf8("leRusRosVeriAralk2"))
        self.leRusRosVeriAralk22 = QtGui.QLineEdit(self.groupBox_4)
        self.leRusRosVeriAralk22.setGeometry(QtCore.QRect(100, 150, 241, 29))
        self.leRusRosVeriAralk22.setObjectName(_fromUtf8("leRusRosVeriAralk22"))
        self.btnRusRosRandomVeri2 = QtGui.QPushButton(self.groupBox_4)
        self.btnRusRosRandomVeri2.setGeometry(QtCore.QRect(10, 210, 341, 41))
        self.btnRusRosRandomVeri2.setObjectName(_fromUtf8("btnRusRosRandomVeri2"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 91, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(390, 310, 120, 271))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.btnRusRosVeriYukle2 = QtGui.QPushButton(self.groupBox_5)
        self.btnRusRosVeriYukle2.setGeometry(QtCore.QRect(20, 20, 81, 241))
        self.btnRusRosVeriYukle2.setObjectName(_fromUtf8("btnRusRosVeriYukle2"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(520, 310, 611, 271))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.twRusRosVeri2 = QtGui.QTableWidget(self.groupBox_6)
        self.twRusRosVeri2.setGeometry(QtCore.QRect(10, 20, 591, 241))
        self.twRusRosVeri2.setObjectName(_fromUtf8("twRusRosVeri2"))
        self.twRusRosVeri2.setColumnCount(0)
        self.twRusRosVeri2.setRowCount(0)
        self.groupBox_7 = QtGui.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 590, 391, 271))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.btnRus = QtGui.QPushButton(self.groupBox_7)
        self.btnRus.setGeometry(QtCore.QRect(10, 20, 371, 29))
        self.btnRus.setObjectName(_fromUtf8("btnRus"))
        self.gvRus = QtGui.QGraphicsView(self.groupBox_7)
        self.gvRus.setGeometry(QtCore.QRect(10, 60, 371, 201))
        self.gvRus.setObjectName(_fromUtf8("gvRus"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(420, 590, 371, 271))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.btnRos = QtGui.QPushButton(self.groupBox_8)
        self.btnRos.setGeometry(QtCore.QRect(10, 20, 351, 29))
        self.btnRos.setObjectName(_fromUtf8("btnRos"))
        self.gvRos = QtGui.QGraphicsView(self.groupBox_8)
        self.gvRos.setGeometry(QtCore.QRect(10, 60, 351, 201))
        self.gvRos.setObjectName(_fromUtf8("gvRos"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab)
        self.groupBox_9.setGeometry(QtCore.QRect(800, 590, 331, 271))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gvRusRos = QtGui.QGraphicsView(self.groupBox_9)
        self.gvRusRos.setGeometry(QtCore.QRect(10, 20, 311, 241))
        self.gvRusRos.setObjectName(_fromUtf8("gvRusRos"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 10, 371, 851))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.twKnnVeri = QtGui.QTableWidget(self.groupBox_10)
        self.twKnnVeri.setGeometry(QtCore.QRect(20, 50, 331, 781))
        self.twKnnVeri.setObjectName(_fromUtf8("twKnnVeri"))
        self.twKnnVeri.setColumnCount(0)
        self.twKnnVeri.setRowCount(0)
        self.btnKnnVeriYukle = QtGui.QPushButton(self.groupBox_10)
        self.btnKnnVeriYukle.setGeometry(QtCore.QRect(20, 20, 331, 29))
        self.btnKnnVeriYukle.setObjectName(_fromUtf8("btnKnnVeriYukle"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_11.setGeometry(QtCore.QRect(400, 10, 731, 301))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gvKnnVeriGrafigi = QtGui.QGraphicsView(self.groupBox_11)
        self.gvKnnVeriGrafigi.setGeometry(QtCore.QRect(20, 30, 691, 251))
        self.gvKnnVeriGrafigi.setObjectName(_fromUtf8("gvKnnVeriGrafigi"))
        self.groupBox_12 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_12.setGeometry(QtCore.QRect(670, 320, 281, 181))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.leKnnVeri1 = QtGui.QLineEdit(self.groupBox_12)
        self.leKnnVeri1.setGeometry(QtCore.QRect(60, 50, 201, 29))
        self.leKnnVeri1.setObjectName(_fromUtf8("leKnnVeri1"))
        self.leKnnVeri2 = QtGui.QLineEdit(self.groupBox_12)
        self.leKnnVeri2.setGeometry(QtCore.QRect(60, 90, 201, 29))
        self.leKnnVeri2.setObjectName(_fromUtf8("leKnnVeri2"))
        self.label_5 = QtGui.QLabel(self.groupBox_12)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_8 = QtGui.QLabel(self.groupBox_12)
        self.label_8.setGeometry(QtCore.QRect(10, 100, 51, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.groupBox_14 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_14.setGeometry(QtCore.QRect(400, 510, 731, 351))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.gvKnnSonucGrafigi = QtGui.QGraphicsView(self.groupBox_14)
        self.gvKnnSonucGrafigi.setGeometry(QtCore.QRect(20, 20, 691, 311))
        self.gvKnnSonucGrafigi.setObjectName(_fromUtf8("gvKnnSonucGrafigi"))
        self.groupBox_13 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_13.setGeometry(QtCore.QRect(400, 320, 261, 181))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.btnKnnKumele = QtGui.QPushButton(self.groupBox_13)
        self.btnKnnKumele.setGeometry(QtCore.QRect(20, 30, 221, 131))
        self.btnKnnKumele.setObjectName(_fromUtf8("btnKnnKumele"))
        self.groupBox_15 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_15.setGeometry(QtCore.QRect(970, 320, 161, 181))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.btnKnnYeniVeriEkleme = QtGui.QPushButton(self.groupBox_15)
        self.btnKnnYeniVeriEkleme.setGeometry(QtCore.QRect(20, 30, 121, 131))
        self.btnKnnYeniVeriEkleme.setObjectName(_fromUtf8("btnKnnYeniVeriEkleme"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_16 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 20, 371, 841))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.twKmeansVeriYukle = QtGui.QTableWidget(self.groupBox_16)
        self.twKmeansVeriYukle.setGeometry(QtCore.QRect(15, 60, 341, 761))
        self.twKmeansVeriYukle.setObjectName(_fromUtf8("twKmeansVeriYukle"))
        self.twKmeansVeriYukle.setColumnCount(0)
        self.twKmeansVeriYukle.setRowCount(0)
        self.btnKmeansVeriYukle = QtGui.QPushButton(self.groupBox_16)
        self.btnKmeansVeriYukle.setGeometry(QtCore.QRect(20, 20, 331, 29))
        self.btnKmeansVeriYukle.setObjectName(_fromUtf8("btnKmeansVeriYukle"))
        self.groupBox_17 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_17.setGeometry(QtCore.QRect(390, 20, 111, 841))
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.btnKmeansVeriKumele = QtGui.QPushButton(self.groupBox_17)
        self.btnKmeansVeriKumele.setGeometry(QtCore.QRect(10, 60, 91, 761))
        self.btnKmeansVeriKumele.setObjectName(_fromUtf8("btnKmeansVeriKumele"))
        self.groupBox_18 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_18.setGeometry(QtCore.QRect(520, 20, 611, 841))
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.gvKmeansVeriKumele = QtGui.QGraphicsView(self.groupBox_18)
        self.gvKmeansVeriKumele.setGeometry(QtCore.QRect(10, 60, 591, 761))
        self.gvKmeansVeriKumele.setObjectName(_fromUtf8("gvKmeansVeriKumele"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.groupBox_19 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_19.setGeometry(QtCore.QRect(100, 80, 561, 131))
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.leNaiveBayes = QtGui.QLineEdit(self.groupBox_19)
        self.leNaiveBayes.setGeometry(QtCore.QRect(20, 50, 521, 41))
        self.leNaiveBayes.setObjectName(_fromUtf8("leNaiveBayes"))
        self.groupBox_20 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_20.setGeometry(QtCore.QRect(680, 80, 381, 361))
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.btnNiveBayesAra = QtGui.QPushButton(self.groupBox_20)
        self.btnNiveBayesAra.setGeometry(QtCore.QRect(20, 20, 341, 321))
        self.btnNiveBayesAra.setObjectName(_fromUtf8("btnNiveBayesAra"))
        self.groupBox_21 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_21.setGeometry(QtCore.QRect(100, 230, 561, 211))
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.lblNaiveBayesSonuc = QtGui.QLabel(self.groupBox_21)
        self.lblNaiveBayesSonuc.setGeometry(QtCore.QRect(120, 90, 281, 31))
        self.lblNaiveBayesSonuc.setText(_fromUtf8(""))
        self.lblNaiveBayesSonuc.setObjectName(_fromUtf8("lblNaiveBayesSonuc"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.groupBox_22 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_22.setGeometry(QtCore.QRect(20, 10, 521, 851))
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.twNormalizasyonVeriYukle = QtGui.QTableWidget(self.groupBox_22)
        self.twNormalizasyonVeriYukle.setGeometry(QtCore.QRect(20, 70, 481, 761))
        self.twNormalizasyonVeriYukle.setObjectName(_fromUtf8("twNormalizasyonVeriYukle"))
        self.twNormalizasyonVeriYukle.setColumnCount(0)
        self.twNormalizasyonVeriYukle.setRowCount(0)
        self.btnNormalizasyonVeriYukle = QtGui.QPushButton(self.groupBox_22)
        self.btnNormalizasyonVeriYukle.setGeometry(QtCore.QRect(20, 30, 481, 31))
        self.btnNormalizasyonVeriYukle.setObjectName(_fromUtf8("btnNormalizasyonVeriYukle"))
        self.groupBox_23 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_23.setGeometry(QtCore.QRect(680, 570, 451, 291))
        self.groupBox_23.setObjectName(_fromUtf8("groupBox_23"))
        self.twNormalizasyonZScore = QtGui.QTableWidget(self.groupBox_23)
        self.twNormalizasyonZScore.setGeometry(QtCore.QRect(10, 20, 431, 261))
        self.twNormalizasyonZScore.setObjectName(_fromUtf8("twNormalizasyonZScore"))
        self.twNormalizasyonZScore.setColumnCount(0)
        self.twNormalizasyonZScore.setRowCount(0)
        self.groupBox_24 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_24.setGeometry(QtCore.QRect(680, 10, 451, 271))
        self.groupBox_24.setObjectName(_fromUtf8("groupBox_24"))
        self.twNormizasyonMinMax = QtGui.QTableWidget(self.groupBox_24)
        self.twNormizasyonMinMax.setGeometry(QtCore.QRect(10, 20, 431, 241))
        self.twNormizasyonMinMax.setObjectName(_fromUtf8("twNormizasyonMinMax"))
        self.twNormizasyonMinMax.setColumnCount(0)
        self.twNormizasyonMinMax.setRowCount(0)
        self.groupBox_25 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_25.setGeometry(QtCore.QRect(680, 290, 451, 271))
        self.groupBox_25.setObjectName(_fromUtf8("groupBox_25"))
        self.twNormalizasyonMedian = QtGui.QTableWidget(self.groupBox_25)
        self.twNormalizasyonMedian.setGeometry(QtCore.QRect(10, 20, 431, 241))
        self.twNormalizasyonMedian.setObjectName(_fromUtf8("twNormalizasyonMedian"))
        self.twNormalizasyonMedian.setColumnCount(0)
        self.twNormalizasyonMedian.setRowCount(0)
        self.groupBox_26 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_26.setGeometry(QtCore.QRect(550, 10, 120, 271))
        self.groupBox_26.setObjectName(_fromUtf8("groupBox_26"))
        self.btnNormizasyonMinMax = QtGui.QPushButton(self.groupBox_26)
        self.btnNormizasyonMinMax.setGeometry(QtCore.QRect(20, 20, 81, 231))
        self.btnNormizasyonMinMax.setObjectName(_fromUtf8("btnNormizasyonMinMax"))
        self.groupBox_27 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_27.setGeometry(QtCore.QRect(550, 290, 120, 271))
        self.groupBox_27.setObjectName(_fromUtf8("groupBox_27"))
        self.btnNormalizasyonMedian = QtGui.QPushButton(self.groupBox_27)
        self.btnNormalizasyonMedian.setGeometry(QtCore.QRect(20, 20, 81, 241))
        self.btnNormalizasyonMedian.setObjectName(_fromUtf8("btnNormalizasyonMedian"))
        self.groupBox_28 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_28.setGeometry(QtCore.QRect(550, 570, 120, 291))
        self.groupBox_28.setObjectName(_fromUtf8("groupBox_28"))
        self.btnNormalizasyonZScore = QtGui.QPushButton(self.groupBox_28)
        self.btnNormalizasyonZScore.setGeometry(QtCore.QRect(20, 30, 81, 251))
        self.btnNormalizasyonZScore.setObjectName(_fromUtf8("btnNormalizasyonZScore"))
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.groupBox_29 = QtGui.QGroupBox(self.tab_9)
        self.groupBox_29.setGeometry(QtCore.QRect(20, 10, 411, 851))
        self.groupBox_29.setObjectName(_fromUtf8("groupBox_29"))
        self.twEgitimTestYukle = QtGui.QTableWidget(self.groupBox_29)
        self.twEgitimTestYukle.setGeometry(QtCore.QRect(15, 60, 381, 771))
        self.twEgitimTestYukle.setObjectName(_fromUtf8("twEgitimTestYukle"))
        self.twEgitimTestYukle.setColumnCount(0)
        self.twEgitimTestYukle.setRowCount(0)
        self.btnEgitimTestYukle = QtGui.QPushButton(self.groupBox_29)
        self.btnEgitimTestYukle.setGeometry(QtCore.QRect(18, 20, 381, 29))
        self.btnEgitimTestYukle.setObjectName(_fromUtf8("btnEgitimTestYukle"))
        self.groupBox_59 = QtGui.QGroupBox(self.tab_9)
        self.groupBox_59.setGeometry(QtCore.QRect(450, 10, 161, 851))
        self.groupBox_59.setObjectName(_fromUtf8("groupBox_59"))
        self.cbEgitim = QtGui.QComboBox(self.groupBox_59)
        self.cbEgitim.setGeometry(QtCore.QRect(20, 40, 121, 141))
        self.cbEgitim.setObjectName(_fromUtf8("cbEgitim"))
        self.cbEgitim.addItem(_fromUtf8(""))
        self.cbEgitim.addItem(_fromUtf8(""))
        self.cbEgitim.addItem(_fromUtf8(""))
        self.cbEgitim.addItem(_fromUtf8(""))
        self.cbEgitim.addItem(_fromUtf8(""))
        self.cbEgitim.addItem(_fromUtf8(""))
        self.cbEgitim.addItem(_fromUtf8(""))
        self.cbEgitim.addItem(_fromUtf8(""))
        self.cbEgitim.addItem(_fromUtf8(""))
        self.btnEgitimTestUygula = QtGui.QPushButton(self.groupBox_59)
        self.btnEgitimTestUygula.setGeometry(QtCore.QRect(20, 210, 121, 621))
        self.btnEgitimTestUygula.setObjectName(_fromUtf8("btnEgitimTestUygula"))
        self.groupBox_60 = QtGui.QGroupBox(self.tab_9)
        self.groupBox_60.setGeometry(QtCore.QRect(630, 10, 501, 331))
        self.groupBox_60.setObjectName(_fromUtf8("groupBox_60"))
        self.twEgitim = QtGui.QTableWidget(self.groupBox_60)
        self.twEgitim.setGeometry(QtCore.QRect(10, 20, 481, 301))
        self.twEgitim.setObjectName(_fromUtf8("twEgitim"))
        self.twEgitim.setColumnCount(0)
        self.twEgitim.setRowCount(0)
        self.groupBox_61 = QtGui.QGroupBox(self.tab_9)
        self.groupBox_61.setGeometry(QtCore.QRect(630, 350, 501, 331))
        self.groupBox_61.setObjectName(_fromUtf8("groupBox_61"))
        self.twTest = QtGui.QTableWidget(self.groupBox_61)
        self.twTest.setGeometry(QtCore.QRect(10, 20, 481, 301))
        self.twTest.setObjectName(_fromUtf8("twTest"))
        self.twTest.setColumnCount(0)
        self.twTest.setRowCount(0)
        self.groupBox_62 = QtGui.QGroupBox(self.tab_9)
        self.groupBox_62.setGeometry(QtCore.QRect(630, 690, 481, 171))
        self.groupBox_62.setObjectName(_fromUtf8("groupBox_62"))
        self.btnRandomForest = QtGui.QPushButton(self.groupBox_62)
        self.btnRandomForest.setGeometry(QtCore.QRect(10, 40, 101, 111))
        self.btnRandomForest.setObjectName(_fromUtf8("btnRandomForest"))
        self.lblRandomForest = QtGui.QLabel(self.groupBox_62)
        self.lblRandomForest.setGeometry(QtCore.QRect(220, 80, 241, 17))
        self.lblRandomForest.setText(_fromUtf8(""))
        self.lblRandomForest.setObjectName(_fromUtf8("lblRandomForest"))
        self.label_11 = QtGui.QLabel(self.groupBox_62)
        self.label_11.setGeometry(QtCore.QRect(130, 80, 91, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.tabWidget.addTab(self.tab_9, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.groupBox_63 = QtGui.QGroupBox(self.tab_10)
        self.groupBox_63.setGeometry(QtCore.QRect(10, 280, 1131, 221))
        self.groupBox_63.setObjectName(_fromUtf8("groupBox_63"))
        self.groupBox_64 = QtGui.QGroupBox(self.groupBox_63)
        self.groupBox_64.setGeometry(QtCore.QRect(10, 20, 531, 191))
        self.groupBox_64.setObjectName(_fromUtf8("groupBox_64"))
        self.twParkinsonSSTEgitim = QtGui.QTableWidget(self.groupBox_64)
        self.twParkinsonSSTEgitim.setGeometry(QtCore.QRect(10, 20, 511, 161))
        self.twParkinsonSSTEgitim.setObjectName(_fromUtf8("twParkinsonSSTEgitim"))
        self.twParkinsonSSTEgitim.setColumnCount(0)
        self.twParkinsonSSTEgitim.setRowCount(0)
        self.groupBox_65 = QtGui.QGroupBox(self.groupBox_63)
        self.groupBox_65.setGeometry(QtCore.QRect(550, 20, 521, 191))
        self.groupBox_65.setObjectName(_fromUtf8("groupBox_65"))
        self.twParkinsonSSTTest = QtGui.QTableWidget(self.groupBox_65)
        self.twParkinsonSSTTest.setGeometry(QtCore.QRect(10, 20, 501, 161))
        self.twParkinsonSSTTest.setObjectName(_fromUtf8("twParkinsonSSTTest"))
        self.twParkinsonSSTTest.setColumnCount(0)
        self.twParkinsonSSTTest.setRowCount(0)
        self.btnParkinsonSST = QtGui.QPushButton(self.groupBox_63)
        self.btnParkinsonSST.setGeometry(QtCore.QRect(1080, 30, 41, 181))
        self.btnParkinsonSST.setObjectName(_fromUtf8("btnParkinsonSST"))
        self.groupBox_69 = QtGui.QGroupBox(self.tab_10)
        self.groupBox_69.setGeometry(QtCore.QRect(10, 510, 1131, 221))
        self.groupBox_69.setObjectName(_fromUtf8("groupBox_69"))
        self.groupBox_70 = QtGui.QGroupBox(self.groupBox_69)
        self.groupBox_70.setGeometry(QtCore.QRect(550, 20, 521, 191))
        self.groupBox_70.setObjectName(_fromUtf8("groupBox_70"))
        self.twParkinsonSTCPTest = QtGui.QTableWidget(self.groupBox_70)
        self.twParkinsonSTCPTest.setGeometry(QtCore.QRect(10, 20, 501, 161))
        self.twParkinsonSTCPTest.setObjectName(_fromUtf8("twParkinsonSTCPTest"))
        self.twParkinsonSTCPTest.setColumnCount(0)
        self.twParkinsonSTCPTest.setRowCount(0)
        self.groupBox_71 = QtGui.QGroupBox(self.groupBox_69)
        self.groupBox_71.setGeometry(QtCore.QRect(10, 20, 531, 191))
        self.groupBox_71.setObjectName(_fromUtf8("groupBox_71"))
        self.twParkinsonSTCPEgitim = QtGui.QTableWidget(self.groupBox_71)
        self.twParkinsonSTCPEgitim.setGeometry(QtCore.QRect(10, 20, 511, 161))
        self.twParkinsonSTCPEgitim.setObjectName(_fromUtf8("twParkinsonSTCPEgitim"))
        self.twParkinsonSTCPEgitim.setColumnCount(0)
        self.twParkinsonSTCPEgitim.setRowCount(0)
        self.btnParkinsonSTCP = QtGui.QPushButton(self.groupBox_69)
        self.btnParkinsonSTCP.setGeometry(QtCore.QRect(1080, 30, 41, 181))
        self.btnParkinsonSTCP.setObjectName(_fromUtf8("btnParkinsonSTCP"))
        self.groupBox_72 = QtGui.QGroupBox(self.tab_10)
        self.groupBox_72.setGeometry(QtCore.QRect(10, 740, 1131, 121))
        self.groupBox_72.setObjectName(_fromUtf8("groupBox_72"))
        self.btnParkinsonRandomForest = QtGui.QPushButton(self.groupBox_72)
        self.btnParkinsonRandomForest.setGeometry(QtCore.QRect(550, 30, 111, 71))
        self.btnParkinsonRandomForest.setObjectName(_fromUtf8("btnParkinsonRandomForest"))
        self.btnParkinsonTumu = QtGui.QPushButton(self.groupBox_72)
        self.btnParkinsonTumu.setGeometry(QtCore.QRect(30, 30, 501, 71))
        self.btnParkinsonTumu.setObjectName(_fromUtf8("btnParkinsonTumu"))
        self.label_15 = QtGui.QLabel(self.groupBox_72)
        self.label_15.setGeometry(QtCore.QRect(670, 60, 51, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lblTahmin = QtGui.QLabel(self.groupBox_72)
        self.lblTahmin.setGeometry(QtCore.QRect(730, 60, 351, 16))
        self.lblTahmin.setText(_fromUtf8(""))
        self.lblTahmin.setObjectName(_fromUtf8("lblTahmin"))
        self.groupBox_66 = QtGui.QGroupBox(self.tab_10)
        self.groupBox_66.setGeometry(QtCore.QRect(10, 40, 1131, 231))
        self.groupBox_66.setObjectName(_fromUtf8("groupBox_66"))
        self.groupBox_67 = QtGui.QGroupBox(self.groupBox_66)
        self.groupBox_67.setGeometry(QtCore.QRect(10, 20, 531, 201))
        self.groupBox_67.setObjectName(_fromUtf8("groupBox_67"))
        self.twParkinsonDSTEgitim = QtGui.QTableWidget(self.groupBox_67)
        self.twParkinsonDSTEgitim.setGeometry(QtCore.QRect(10, 20, 511, 171))
        self.twParkinsonDSTEgitim.setObjectName(_fromUtf8("twParkinsonDSTEgitim"))
        self.twParkinsonDSTEgitim.setColumnCount(0)
        self.twParkinsonDSTEgitim.setRowCount(0)
        self.groupBox_68 = QtGui.QGroupBox(self.groupBox_66)
        self.groupBox_68.setGeometry(QtCore.QRect(550, 20, 521, 201))
        self.groupBox_68.setObjectName(_fromUtf8("groupBox_68"))
        self.twParkinsonDSTTest = QtGui.QTableWidget(self.groupBox_68)
        self.twParkinsonDSTTest.setGeometry(QtCore.QRect(10, 20, 501, 171))
        self.twParkinsonDSTTest.setObjectName(_fromUtf8("twParkinsonDSTTest"))
        self.twParkinsonDSTTest.setColumnCount(0)
        self.twParkinsonDSTTest.setRowCount(0)
        self.btnParkinsonDST = QtGui.QPushButton(self.groupBox_66)
        self.btnParkinsonDST.setGeometry(QtCore.QRect(1080, 30, 41, 191))
        self.btnParkinsonDST.setObjectName(_fromUtf8("btnParkinsonDST"))
        self.btnParkinsonVeriYukle = QtGui.QPushButton(self.tab_10)
        self.btnParkinsonVeriYukle.setGeometry(QtCore.QRect(10, 10, 1131, 31))
        self.btnParkinsonVeriYukle.setObjectName(_fromUtf8("btnParkinsonVeriYukle"))
        self.tabWidget.addTab(self.tab_10, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "1. Eklenecek Veri Miktar Ve  Aralığı", None))
        self.label.setText(_translate("Dialog", "Veri Miktari       :", None))
        self.label_2.setText(_translate("Dialog", "1. Veri Araliği    :", None))
        self.btnRusRosRandomVeri1.setText(_translate("Dialog", "Random Veri Olustur", None))
        self.label_6.setText(_translate("Dialog", "2. Veri Araliği   :", None))
        self.groupBox_2.setTitle(_translate("Dialog", "1.Hazir Veri EKle", None))
        self.btnRusRosVeriYukle1.setText(_translate("Dialog", "Yükle", None))
        self.groupBox_3.setTitle(_translate("Dialog", "1.Veri Listesi", None))
        self.groupBox_4.setTitle(_translate("Dialog", "2. Eklenecek Veri Miktar Ve  Aralığı", None))
        self.label_3.setText(_translate("Dialog", "Veri Miktari    :", None))
        self.label_4.setText(_translate("Dialog", "1.Veri Araliği  :", None))
        self.btnRusRosRandomVeri2.setText(_translate("Dialog", "Random Veri Olustur", None))
        self.label_7.setText(_translate("Dialog", "2. Veri Araliği :", None))
        self.groupBox_5.setTitle(_translate("Dialog", "2.Hazir Veri EKle", None))
        self.btnRusRosVeriYukle2.setText(_translate("Dialog", "Yükle", None))
        self.groupBox_6.setTitle(_translate("Dialog", "2.Veri Listesi", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Rus", None))
        self.btnRus.setText(_translate("Dialog", "Gerçekleştir", None))
        self.groupBox_8.setTitle(_translate("Dialog", "Ros", None))
        self.btnRos.setText(_translate("Dialog", "Gerçekleştir", None))
        self.groupBox_9.setTitle(_translate("Dialog", "Ham Veri Grafiği", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "RUS-ROS VE RANDOMİZE VERİ", None))
        self.groupBox_10.setTitle(_translate("Dialog", "Ham Veri", None))
        self.btnKnnVeriYukle.setText(_translate("Dialog", "Yükle", None))
        self.groupBox_11.setTitle(_translate("Dialog", "Ham Verinin Grafiği", None))
        self.groupBox_12.setTitle(_translate("Dialog", "Veri Ekleme Ekranı ", None))
        self.label_5.setText(_translate("Dialog", "1. Veri :", None))
        self.label_8.setText(_translate("Dialog", "2. Veri :", None))
        self.groupBox_14.setTitle(_translate("Dialog", "GroupBox", None))
        self.groupBox_13.setTitle(_translate("Dialog", "Kümele İşlmeini Yap", None))
        self.btnKnnKumele.setText(_translate("Dialog", "Kümele", None))
        self.groupBox_15.setTitle(_translate("Dialog", "Yeni Veri Ekle", None))
        self.btnKnnYeniVeriEkleme.setText(_translate("Dialog", "Yükle", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "KNN-EN YAKIN KOMŞULUK", None))
        self.groupBox_16.setTitle(_translate("Dialog", "Ham Veri", None))
        self.btnKmeansVeriYukle.setText(_translate("Dialog", "Yükle", None))
        self.groupBox_17.setTitle(_translate("Dialog", "K - Means", None))
        self.btnKmeansVeriKumele.setText(_translate("Dialog", "Kumele", None))
        self.groupBox_18.setTitle(_translate("Dialog", "Grafiği", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "K-MEANS", None))
        self.groupBox_19.setTitle(_translate("Dialog", "Tahmini Yapılacak Kelimeyi Gir", None))
        self.groupBox_20.setTitle(_translate("Dialog", "Naive Bayes ", None))
        self.btnNiveBayesAra.setText(_translate("Dialog", "Tahmin Yap", None))
        self.groupBox_21.setTitle(_translate("Dialog", "Tahmin Sonucu ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "NAİVE BAYES", None))
        self.groupBox_22.setTitle(_translate("Dialog", "Ham Veri", None))
        self.btnNormalizasyonVeriYukle.setText(_translate("Dialog", "Yükle", None))
        self.groupBox_23.setTitle(_translate("Dialog", "Z-Score", None))
        self.groupBox_24.setTitle(_translate("Dialog", "Min-Max", None))
        self.groupBox_25.setTitle(_translate("Dialog", "Median", None))
        self.groupBox_26.setTitle(_translate("Dialog", "Min-Max", None))
        self.btnNormizasyonMinMax.setText(_translate("Dialog", "Gerçekleştir", None))
        self.groupBox_27.setTitle(_translate("Dialog", "Median", None))
        self.btnNormalizasyonMedian.setText(_translate("Dialog", "Gerçekleştir", None))
        self.groupBox_28.setTitle(_translate("Dialog", "Z-Score", None))
        self.btnNormalizasyonZScore.setText(_translate("Dialog", "Gerçekleştir", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Dialog", "NORMALİZASYON", None))
        self.groupBox_29.setTitle(_translate("Dialog", "Ham Veriler", None))
        self.btnEgitimTestYukle.setText(_translate("Dialog", "Yükle", None))
        self.groupBox_59.setTitle(_translate("Dialog", "Test Veri Miktari %", None))
        self.cbEgitim.setItemText(0, _translate("Dialog", "10", None))
        self.cbEgitim.setItemText(1, _translate("Dialog", "20", None))
        self.cbEgitim.setItemText(2, _translate("Dialog", "30", None))
        self.cbEgitim.setItemText(3, _translate("Dialog", "40", None))
        self.cbEgitim.setItemText(4, _translate("Dialog", "50", None))
        self.cbEgitim.setItemText(5, _translate("Dialog", "60", None))
        self.cbEgitim.setItemText(6, _translate("Dialog", "70", None))
        self.cbEgitim.setItemText(7, _translate("Dialog", "80", None))
        self.cbEgitim.setItemText(8, _translate("Dialog", "90", None))
        self.btnEgitimTestUygula.setText(_translate("Dialog", "Uygula", None))
        self.groupBox_60.setTitle(_translate("Dialog", "Eğitim Verileri", None))
        self.groupBox_61.setTitle(_translate("Dialog", "Test Verileri", None))
        self.groupBox_62.setTitle(_translate("Dialog", "Random Forest İle Tahmin Yapma ", None))
        self.btnRandomForest.setText(_translate("Dialog", "Random Forest", None))
        self.label_11.setText(_translate("Dialog", "Tahmin Orani :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("Dialog", "EĞİTİM-TEST VE RANDOM FOREST", None))
        self.groupBox_63.setTitle(_translate("Dialog", "SST", None))
        self.groupBox_64.setTitle(_translate("Dialog", "Eğitim", None))
        self.groupBox_65.setTitle(_translate("Dialog", "Test", None))
        self.btnParkinsonSST.setText(_translate("Dialog", "SST", None))
        self.groupBox_69.setTitle(_translate("Dialog", "STCP", None))
        self.groupBox_70.setTitle(_translate("Dialog", "Test", None))
        self.groupBox_71.setTitle(_translate("Dialog", "Eğitim", None))
        self.btnParkinsonSTCP.setText(_translate("Dialog", "STCP", None))
        self.groupBox_72.setTitle(_translate("Dialog", "Tahminler ", None))
        self.btnParkinsonRandomForest.setText(_translate("Dialog", "Random Forest", None))
        self.btnParkinsonTumu.setText(_translate("Dialog", "Tümünü Ver", None))
        self.label_15.setText(_translate("Dialog", "Tahmin :", None))
        self.groupBox_66.setTitle(_translate("Dialog", "DST", None))
        self.groupBox_67.setTitle(_translate("Dialog", "Eğitim", None))
        self.groupBox_68.setTitle(_translate("Dialog", "Test", None))
        self.btnParkinsonDST.setText(_translate("Dialog", "DST", None))
        self.btnParkinsonVeriYukle.setText(_translate("Dialog", "Veri Yükle", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("Dialog", "PARKİNSON", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

